### ISSUE TITLE
No help description for `volttron -vv` command

### ISSUE THREAD

**Issue by kefeimo** [eclipse-volttron/volttron-core#149]
**Describe the bug**
For volttron 10.0.3a2, the help (i.e., -h, --help) command doesn't list `-vv` subcommand, e.g., when using `volttron -vv -l volttron.log &>/dev/null &` 

**To Reproduce**
run `volttron -h` or `volttron -vv -h`

**Expected behavior**
Describe what `-vv` does

**Screenshots**
![image](https://user-images.githubusercontent.com/28743873/214897129-2b3a29e7-c72e-4623-b681-c26823a99456.png)

**Comment by craig8** [comment]
Use volttron --help to get the following

![image](https://user-images.githubusercontent.com/3979063/216193305-b25194b1-d298-4aaa-bcaa-ce92574eb08c.png)
