### ISSUE TITLE
Support and provide guidance for with-comment-json config

### ISSUE THREAD

**Issue by kefeimo** [eclipse-volttron/volttron-core#178]
## Motivation:
Json-like format is widely accepted as Volttron agent config file. However, the standard json format doesn't allow comments, which impeds config file readability.

## Expectation:
Support json file with comments as config file, e.g., when using `vctl install --agent-config`.

Ref: [JSON Comments: Complete Guide with Examples](https://reqbin.com/json/5wzepqmt/json-comment-example#:~:text=Can%20I%20add%20a%20comment,elements%20will%20still%20be%20data.)

**Comment by craig8** [comment]
So our agent configs already support # style comments. 

Though editors and IDE's don't really support that natively.

**Comment by kefeimo** [comment]
Mentioned here at https://volttron.readthedocs.io/en/main/platform-features/config-store/configuration-store.html?highlight=json%20comment#json.

> ... it supports Python style comments and must create an object or list when parsed.

Sorry for missing that. 
Closed accordingly.
