### ISSUE TITLE
Potential zombie agent process after killing the volttron platform

### ISSUE THREAD

**Issue by kefeimo** [eclipse-volttron/volttron-core#180]
**Describe the bug**
As seen in the following screenshot, after killing the VOLTTRON platform, it didn't kill the agent process immediately
![image](https://github.com/eclipse-volttron/volttron-core/assets/28743873/5b128349-b263-4e5c-a5fa-cc817779c18e)

**To Reproduce**
1. start the platform
2. start an agent (e.g., listener-agent)
3. kill the volttron platform process
4. immediately check the agent process status (ps aux | grep listener)

** Note: at some extreme case, the agent cannot run properly even after the platform is shutdown. (Cannot reproduce though.)

**Comment by schandrika** [comment]
Fixed in version 2.0.0rc0
