### ISSUE TITLE
volttron_home not starting without full path. 

### ISSUE THREAD

**Issue by riley206** [eclipse-volttron/volttron-core#190]
**Description**
when setting VOLTTRON_HOME to a relative path using export VOLTTRON_HOME=, It will (most of the time) throw an error not allowing you to start the platform.  

**To Reproduce**
1. Install volttron 
2. export VOLTTRON_HOME=/some/relative/path
3. start the platform
4. See error volttron.server.__main__(210) DEBUG: opts.instancename None

**Expected behavior**
I expect volttron to understand this relative path and correctly use it. 

**Operating System:**
 - OS: Ubuntu (WSL)
 - volttron-core [develop]

**Comment by schandrika** [comment]
fixed in 2.0.0rc0
