### ISSUE TITLE
Issue with volttron-core v10 and pip

### ISSUE THREAD

**Issue by riley206** [eclipse-volttron/volttron-core#219]
**Screenshots**
![image](https://github.com/user-attachments/assets/023cd28d-d676-45f3-b7af-8675e25fa458)

**Comment by craig8** [comment]
@riley206 can you confirm upgrading to the latest pip fixed this issue?

**Comment by craig8** [comment]
Please add context.  I see this is raspberry pi.  not 100% sure here.

**Comment by schandrika** [comment]
resolved by upgrading pip. updated readme with pip version requirement
